volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres:15
    container_name: turborepo_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: turborepo
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
