# fly.toml app configuration file generated for server-snowy-river-5141 on 2024-12-10T23:23:14+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-snowy-river-5141'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
